changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
    - title: ⚠️ Breaking Changes
      labels:
        - breaking
