changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - dependencies
    - title: 📖 Documentation
      labels:
        - documentation
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
    - title: 🔖 Other Changes
      labels:
        - "*"