package io.fletchly.comparator.core.model.message

/**
 * Message in a conversation
 */
sealed interface Message {
    val content: String

    /**
     * Message sent by a human user
     */
    class User(override val content: String) : Message

    /**
     * Message generated by an AI assistant
     *
     * @param toolCalls list of tools to execute
     */
    class Assistant(override val content: String, val toolCalls: List<ToolCall>? = null) : Message

    /**
     * Message returned by a tool call
     */
    class Tool(override val content: String) : Message

    /**
     * System-level instruction for an AI assistant
     */
    class System(override val content: String) : Message
}