/*
 * This file is part of comparator, licensed under the Apache License 2.0
 *
 * Copyright (c) 2026 fletchly <https://github.com/fletchly>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.fletchly.comparator.model.tool

import io.fletchly.comparator.exception.ToolException
import kotlinx.serialization.KSerializer

/**
 * Represents the result of executing a tool.
 *
 * This sealed interface is used to categorize and store the outcome of a tool execution,
 * which can either be a success or a failure. A result always contains the name of the tool
 * that generated it.
 */
sealed interface ToolResult {
    val toolName: String

    /**
     * Represents the successful execution result of a tool.
     *
     * This class is a concrete implementation of the [ToolResult] interface,
     * encapsulating the tool's successful output and its associated metadata.
     *
     * @property toolName The name of the tool that produced this result.
     * @property value The actual result data generated by the tool.
     * @property serializer The [KSerializer] used to serialize or deserialize the result data.
     */
    data class Success(
        override val toolName: String,
        val value: Any,
        val serializer: KSerializer<out Any>
    ) : ToolResult

    /**
     * Represents a failure that occurred during the execution of a tool.
     *
     * This class is a concrete implementation of the [ToolResult] interface,
     * used to encapsulate the details of an error that arose while executing a tool.
     * It includes the name of the tool that experienced the failure and the
     * associated [ToolException] containing error information.
     *
     * @property toolName The name of the tool where the failure occurred.
     * @property error The [ToolException] representing the error details.
     */
    data class Failure(
        override val toolName: String,
        val error: ToolException
    ) : ToolResult
}