/*
 * This file is part of comparator, licensed under the Apache License 2.0
 *
 * Copyright (c) 2026 fletchly <https://github.com/fletchly>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.fletchly.comparator.model.message

/**
 * Represents a message exchanged in a system, which can be sent by a user,
 * generated by an AI assistant, or returned by a tool call.
 */
sealed interface Message {
    val content: String


    /**
     * Represents a message sent by a user in the system.
     *
     * This class implements the `Message` interface and is used to encapsulate
     * information about user-generated messages in a conversation. Each user
     * message is associated with its content and the `Actor` who sent it.
     *
     * @property content The content of the message.
     * @property sender The actor who sent the message.
     */
    class User(override val content: String, val sender: io.fletchly.comparator.model.user.User) : Message

    /**
     * Represents a message generated by an AI assistant in a conversational system.
     *
     * This class implements the `Message` interface and is used to encapsulate
     * responses from the assistant. These responses may include a list of tool calls
     * for further execution.
     *
     * @property content The textual content of the assistant's response.
     * @property toolCalls An optional list of tool calls associated with the response,
     *                     which can be used to trigger external actions or queries.
     */
    class Assistant(override val content: String, val toolCalls: List<ToolCall>? = null) : Message


    /**
     * Represents a message generated as the result of a tool's execution in a system.
     *
     * This class implements the `Message` interface and is used to encapsulate the
     * response content produced by a tool after it has been executed successfully.
     * The `Tool` message serves as a mechanism for tools to communicate results or
     * outputs back into the system.
     *
     * @property content The textual content of the tool's response or output.
     */
    class Tool(override val content: String) : Message
}